from .client import BangumiClient
from .exceptions import BangumiApiError
from .models import (
    Avatar,
    CollectionSummary,
    CollectionUpdate,
    CurrentUser,
    Episode,
    EpisodeCollection,
    EpisodeCollectionType,
    EpisodeCollectionUpdate,
    PagedEpisodeCollections,
    Images,
    InfoBoxItem,
    InfoBoxValue,
    PagedSubjects,
    PagedUserSubjectCollections,
    Rating,
    RatingCount,
    SearchSort,
    SlimSubject,
    Subject,
    SubjectCollectionType,
    SubjectSearchFilter,
    SubjectTag,
    SubjectType,
    User,
    UserGroup,
    UserSubjectCollection,
)

__version__ = "0.1.0"

__all__ = [
    "Avatar",
    "BangumiApiError",
    "BangumiClient",
    "CollectionSummary",
    "CollectionUpdate",
    "CurrentUser",
    "Episode",
    "EpisodeCollection",
    "EpisodeCollectionType",
    "EpisodeCollectionUpdate",
    "PagedEpisodeCollections",
    "Images",
    "InfoBoxItem",
    "InfoBoxValue",
    "PagedSubjects",
    "PagedUserSubjectCollections",
    "Rating",
    "RatingCount",
    "SearchSort",
    "SlimSubject",
    "Subject",
    "SubjectCollectionType",
    "SubjectSearchFilter",
    "SubjectTag",
    "SubjectType",
    "User",
    "UserGroup",
    "UserSubjectCollection",
    "__version__",
]
